### ISSUE TITLE
Pull request fix: Toasts background hiding action buttons and task names

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/Utilities#13]
Hi,

On some devices, the toasts background can be really annoying and masking the tasks name and buttons
This one was bothering me since a few months and I never had time to look at it. It is mainly annoying when deleting/renaming/copying tasks as the action buttons were hidden and we have to wait for next action.

I just pushed a proper fix that also preserves the corners radius effect. We can continue to see and access the bottom action buttons freely while toast is there. This is also better than a wasted touch to dismiss the toast or to wait to see the buttons to touch

Before:
<img width="324" alt="Screenshot_1601132303" src="https://user-images.githubusercontent.com/2428217/94343787-f1c06680-001a-11eb-85ec-8ce3f900df64.png">

After:
<img width="324" alt="Screenshot_1601132097" src="https://user-images.githubusercontent.com/2428217/94343788-f71db100-001a-11eb-83a9-bc4effd35020.png">

Best regards

**Comment by Sentaroh** [comment]
Thank you

I am merged "Toasts background hiding action buttons and task names".
However, I don't agree with Translucent because it makes the text difficult to read.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Hi,
I am used to Samsung phones and Android Stock source phones which all have their apps with toasts as transparent by default

**Here are some screen shots from Samsung built in apps (clock app and Samsung Note app):**
<img width="432" alt="Screenshot_2020-09-27-13-58-47-res" src="https://user-images.githubusercontent.com/2428217/94364939-458b8800-00cd-11eb-9e4d-6cbe109ccfca.png">
<img width="432" alt="Screenshot_2020-09-27-13-55-49-res" src="https://user-images.githubusercontent.com/2428217/94364941-46241e80-00cd-11eb-895b-605598202c0f.png">


**Here's a Google Phone (stock Android) toast message from Gmail:**
<img width="539" alt="Screenshot_20200927-140711" src="https://user-images.githubusercontent.com/2428217/94364676-7bc80800-00cb-11eb-8bd2-a0801920f78f.png">

Most modern apps provide some transparency because it is really annoying to have a non asked toast regularly hiding your text and touch buttons for a few seconds

What I suggest:
- No transparency for context help toasts because they are asked by user and are small in size:
`static private void setToastMessageView(Activity a, View custom_toast_view, TextView toast_message)`

- Add some alpha transparency for the app system toasts, mainly the frequent "Synchronization settings were automatically saved" :
`static private Toast showToast(Activity a, String msg, int duration)`

This is in harmony with Android OS toasts also

- A last thing:
Make the app system toasts "Synchronization settings were automatically saved" smaller also: something like "Settings saved" is enough I think so that this frequent toast gets less intrusive also in size. Even in french it would be small "Paramètres sauvegardés"

Let me know and best regards

**Comment by PhilZ-cwm6** [comment]
I added a pull request to give an example
Also, I shortened the text in SMBSync2 pull request. I think it is good independently of the opacity if you agree or not

Best regards

**Comment by PhilZ-cwm6** [comment]
I added a pull request to give an example
I also added a second commit with background = white and opacity = 90%
<img width="324" alt="Screenshot_1601218930" src="https://user-images.githubusercontent.com/2428217/94368291-93ab8600-00e3-11eb-9e73-3433e79b4103.png">

And better with a small white tinted, but less then the stock LTGREY
<img width="324" alt="Screenshot_1601219722" src="https://user-images.githubusercontent.com/2428217/94368622-665fd780-00e5-11eb-8e49-14df25db63e8.png">

The contrast and visibility are better and match better Android sources (I am not sure about Gmail opacity but background looks to be a light tinted white)

The visibility/contrast is much better now and we have the visibility behind

Anyway, hope it helps you decide or implement a small more modern transparency effect

Best regards

**Comment by PhilZ-cwm6** [comment]
Ok, I found the last issue: it was the font size 
The Context button help toasts use your customView with font size Medium in xml
The Android default size of the other toasts is small

We got 2 toasts with two different sizes
I committed a proper patch, unless you want to migrate all toasts to your custom view

Fixed image (compare to previous post with default small size)
<img width="324" alt="Screenshot_1601222361" src="https://user-images.githubusercontent.com/2428217/94369836-631c1a00-00ec-11eb-98a7-2e4842845f95.png">

The help toasts are kept to your custom optimal size:
<img width="324" alt="Screenshot_1601222982" src="https://user-images.githubusercontent.com/2428217/94369886-aaa2a600-00ec-11eb-8cd8-dee1d9e900f5.png">


Hope it is ok to merge. The 90% opacity seems good contrast and visibility now that font size and background color are adjusted

Best regards

**Comment by Sentaroh** [comment]
Thank you.

Your changes have been incorporated.
Added common creation of views for popup messages and toast messages.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Ah yes, really nice now and good contrast despite you reverted to small text
I have a rather bad vision but the small font is better with the custom toast layout

Thank you and best regards
